# Site settings
title: WrinklyNinja’s Workshop
email: oliver.hamlet@gmail.com
author: Oliver Hamlet
description: A collection of words about code and related matters.
baseurl: ""
url: "https://wrinklyninja.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username:  WrinklyNinja
twitter_username: OliverHamlet
linkedin_username: oliverhamlet
bitcoin_url: /bitcoin/
paypal_url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=HDR3YBGGYCLBG
flattr_button: "<script id='fbapcfm'>(function(i){var f,s=document.getElementById(i);f=document.createElement('iframe');f.src='//api.flattr.com/button/view/?uid=OliverHamlet&button=compact&url=https%3A%2F%2Fwrinklyninja.github.io';f.title='Flattr';f.height=20;f.width=110;f.style.borderWidth=0;s.parentNode.insertBefore(f,s);})('fbapcfm');</script>"

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true

# Kramdown settings
kramdown:
  input: GFM

# GitHub-supported Jekyll gems
gems:
  - jekyll-mentions
  - jemoji
