# Site settings
title: WrinklyNinja’s Workshop
author: Oliver Hamlet
email: oliver.hamlet@gmail.com
url: "https://wrinklyninja.github.io"
description: >
  A collection of words about code and related matters.

# Nuts and Bolts settings
baseurl: ""
google_analytics:

# Social settings
twitter_username: OliverHamlet
github_username:  WrinklyNinja
linkedin_username: oliverhamlet
paypal_url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=HDR3YBGGYCLBG
google_plus_id: 104661746805670028939

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3

# Kramdown settings
kramdown:
  input: GFM
